-- Migracion 002: Reportes graficos, modalidades de plan y entidad Cancha.
--
-- Contexto: el cliente pidio reportes graficos para Gimnasio (ocupacion
-- mensual S1..S4), Cancha (ingreso diario D1..D30) y Cantina (recaudacion
-- diaria sobre efectivo cierre + stock cierre), mas modalidades de
-- inscripcion en Plan y nueva ficha de alumno.
--
-- Esta migracion crea:
--   1. Tabla configuracion (clave/valor) con seeds para las constantes R y $T.
--   2. Columnas en plan: PlanModalidad, PlanCantidadClases.
--   3. Columna en suscripcion: SuscripcionClasesRestantes.
--   4. Tablas cancha y cancha_reserva (reservas + ingresos).
--
-- Convenciones del proyecto:
--   - Nombres de tablas/columnas SIN comillas (PG los guarda en minusculas).
--   - PK con sequence nombrada `<tabla>_<col>_seq` y default nextval(...).
--   - Booleanos como SMALLINT (0/1) para mantener el patron de las demas tablas.
--   - Fechas NOT NULL con default '1900-01-01' como centinela.
--
-- Ejecucion: idempotente. Usa CREATE TABLE IF NOT EXISTS y ADD COLUMN IF NOT
-- EXISTS, asi que correr de nuevo no rompe nada.

BEGIN;

-- ============================================================
-- 1. Tabla `configuracion`
-- ============================================================
CREATE TABLE IF NOT EXISTS configuracion (
  configclave        VARCHAR(64)  PRIMARY KEY,
  configvalor        TEXT         NOT NULL DEFAULT '',
  configdescripcion  VARCHAR(255) NOT NULL DEFAULT '',
  configtipo         VARCHAR(16)  NOT NULL DEFAULT 'TEXTO'
);

-- Seeds: solo si no existen aun (no pisar valores que el usuario ya edito).
INSERT INTO configuracion (configclave, configvalor, configdescripcion, configtipo)
VALUES
  ('GIMNASIO_CAPACIDAD_MENSUAL', '250',    'Capacidad total de clases por mes del gimnasio (R)', 'NUMERO'),
  ('CANCHA_META_DIARIA',         '800000', 'Meta diaria de ingreso por cancha en guaranies ($T)', 'MONTO'),
  ('GIMNASIO_NOMBRE',            '',       'Nombre del gimnasio para ficha y reportes', 'TEXTO')
ON CONFLICT (configclave) DO NOTHING;

-- ============================================================
-- 2. Columnas nuevas en `plan`
-- ============================================================
--   PlanModalidad: 'MENSUAL' (default), 'CLASES' (cupo finito), 'OPEN' (pase libre).
--   PlanCantidadClases: solo aplica cuando PlanModalidad='CLASES'.
ALTER TABLE plan
  ADD COLUMN IF NOT EXISTS planmodalidad      VARCHAR(16) NOT NULL DEFAULT 'MENSUAL',
  ADD COLUMN IF NOT EXISTS plancantidadclases SMALLINT    NOT NULL DEFAULT 0;

-- ============================================================
-- 3. Columna nueva en `suscripcion`
-- ============================================================
--   SuscripcionClasesRestantes: solo aplica cuando el plan asociado es 'CLASES'.
ALTER TABLE suscripcion
  ADD COLUMN IF NOT EXISTS suscripcionclasesrestantes SMALLINT NOT NULL DEFAULT 0;

-- ============================================================
-- 4. Tabla `cancha` (canchas disponibles para reserva)
-- ============================================================
CREATE TABLE IF NOT EXISTS cancha (
  canchaid         INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canchanombre     VARCHAR(120) NOT NULL DEFAULT '',
  canchatarifahora BIGINT       NOT NULL DEFAULT 0,
  canchaactiva     SMALLINT     NOT NULL DEFAULT 1
);

-- Seed de una cancha por defecto para empezar a operar.
INSERT INTO cancha (canchanombre, canchatarifahora, canchaactiva)
SELECT 'Cancha Principal', 0, 1
WHERE NOT EXISTS (SELECT 1 FROM cancha);

-- ============================================================
-- 5. Tabla `cancha_reserva` (reservas + ingresos de cancha)
-- ============================================================
--   Estados:
--     'R' = Reservada (sin pagar)
--     'P' = Pagada (genera ingreso del dia)
--     'X' = Cancelada (no cuenta para ingresos)
CREATE TABLE IF NOT EXISTS cancha_reserva (
  canchareservaid           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canchaid                  INTEGER      NOT NULL DEFAULT 0,
  clienteid                 INTEGER      NULL,
  canchareservacliente      VARCHAR(255) NOT NULL DEFAULT '',
  canchareservafecha        DATE         NOT NULL DEFAULT '1900-01-01',
  canchareservahorainicio   TIMESTAMP    NOT NULL DEFAULT '1900-01-01 00:00:00',
  canchareservahorafin      TIMESTAMP    NOT NULL DEFAULT '1900-01-01 00:00:00',
  canchareservamonto        BIGINT       NOT NULL DEFAULT 0,
  canchareservaestado       VARCHAR(2)   NOT NULL DEFAULT 'R',
  canchareservaobservacion  VARCHAR(255) NOT NULL DEFAULT '',
  usuarioid                 VARCHAR(64)  NULL,
  canchareservacreadoen     TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Indice util para el reporte diario y para listar reservas de un dia.
CREATE INDEX IF NOT EXISTS idx_cancha_reserva_fecha ON cancha_reserva (canchareservafecha);
CREATE INDEX IF NOT EXISTS idx_cancha_reserva_estado_fecha ON cancha_reserva (canchareservaestado, canchareservafecha);

COMMIT;
