-- Migracion 006: Tarifas por banda horaria para Cancha.
--
-- Hasta ahora cada cancha tenia una tarifa flat (CanchaTarifaHora). El cliente
-- pidio soporte para bandas: combinacion de dias de semana + rango horario
-- con su precio propio. Ej.:
--   "Lun-Vie 06:00-18:00 = Gs.50.000/h"
--   "Lun-Vie 18:00-23:00 = Gs.80.000/h"
--   "Sab-Dom todo el dia  = Gs.100.000/h"
--
-- Decisiones de modelado:
--   - Tarifas por cancha (no globales): mas flexible si hay canchas diferentes.
--   - Dias de semana se guardan como string CSV con letras L,M,X,J,V,S,D.
--   - Hora desde/hasta como TIME (sin fecha) — el banda se evalua por hora del dia.
--   - Prioridad: cuando dos bandas matchean el mismo horario, gana la de mayor
--     valor. Default 0. Util para tener una banda general + una excepcion.
--
-- La columna `cancha.CanchaTarifaHora` se mantiene como fallback cuando no
-- hay bandas configuradas (compatibilidad con reservas viejas y canchas
-- nuevas sin tarifa definida).
--
-- Tambien registra el menu CANCHATARIFA y permisos para perfil ADMINISTRADOR
-- y GIMNASIO.

BEGIN;

CREATE TABLE IF NOT EXISTS cancha_tarifa (
  canchatarifaid          INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canchaid                INTEGER     NOT NULL,
  canchatarifanombre      VARCHAR(120) NOT NULL DEFAULT '',
  canchatarifadiassemana  VARCHAR(16) NOT NULL DEFAULT 'L,M,X,J,V,S,D',
  canchatarifahoradesde   TIME        NOT NULL DEFAULT '00:00:00',
  canchatarifahorahasta   TIME        NOT NULL DEFAULT '23:59:59',
  canchatarifaprecio      BIGINT      NOT NULL DEFAULT 0,
  canchatarifaprioridad   SMALLINT    NOT NULL DEFAULT 0,
  canchatarifaactiva      SMALLINT    NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_cancha_tarifa_cancha
  ON cancha_tarifa (canchaid, canchatarifaactiva);

-- Menu + permisos al admin y al perfil GIMNASIO.
INSERT INTO menu (MenuId, MenuNombre) VALUES ('CANCHATARIFA', 'CANCHATARIFA')
ON CONFLICT (menuid) DO NOTHING;

INSERT INTO perfilmenu (PerfilId, MenuId, puedeCrear, puedeEditar, puedeEliminar, puedeLeer)
VALUES
  (1, 'CANCHATARIFA', 1, 1, 1, 1),
  (4, 'CANCHATARIFA', 1, 1, 1, 1)
ON CONFLICT (perfilid, menuid) DO UPDATE SET
  puedecrear    = EXCLUDED.puedecrear,
  puedeeditar   = EXCLUDED.puedeeditar,
  puedeeliminar = EXCLUDED.puedeeliminar,
  puedeleer     = EXCLUDED.puedeleer;

COMMIT;
