-- Migracion 009: Sistema de creditos para canchas.
--
-- Cuando una reserva se cobra con metodo "Credito" (CR), parte del monto
-- queda como deuda del cliente. Hasta ahora ese cobro generaba la fila en
-- registrodiariocaja pero NO se persistia como deuda — el sistema de
-- /credito-pagos solo conocia ventacredito (deudas de ventas de cantina),
-- asi que las deudas de cancha quedaban invisibles.
--
-- Replica el patron de ventacredito / ventacreditopago:
--   - cancha_credito: cabecera por reserva con monto original + saldo
--   - cancha_credito_pago: pagos parciales que se aplican al saldo
--
-- ClienteId es NOT NULL porque ya validamos en el endpoint /cobrar que no se
-- puede usar CR para reservas de invitados (no hay forma de perseguir la
-- deuda sin un cliente registrado).
--
-- Idempotente: CREATE TABLE IF NOT EXISTS.

BEGIN;

CREATE TABLE IF NOT EXISTS cancha_credito (
  canchacreditoid        INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canchareservaid        INTEGER     NOT NULL,
  clienteid              INTEGER     NOT NULL,
  canchacreditomonto     BIGINT      NOT NULL DEFAULT 0,
  canchacreditosaldo     BIGINT      NOT NULL DEFAULT 0,
  canchacreditofecha     TIMESTAMP   NOT NULL DEFAULT NOW(),
  canchacreditopagocant  INTEGER     NOT NULL DEFAULT 0,
  usuarioid              VARCHAR(25)
);

CREATE INDEX IF NOT EXISTS idx_cancha_credito_cliente
  ON cancha_credito (clienteid)
  WHERE canchacreditosaldo > 0;

CREATE INDEX IF NOT EXISTS idx_cancha_credito_reserva
  ON cancha_credito (canchareservaid);

CREATE TABLE IF NOT EXISTS cancha_credito_pago (
  canchacreditoid          INTEGER     NOT NULL,
  canchacreditopagoid      INTEGER     NOT NULL,
  canchacreditopagofecha   TIMESTAMP   NOT NULL DEFAULT NOW(),
  canchacreditopagomonto   BIGINT      NOT NULL DEFAULT 0,
  canchacreditopagotipo    VARCHAR(2)  NOT NULL,
  usuarioid                VARCHAR(25),
  PRIMARY KEY (canchacreditoid, canchacreditopagoid)
);

COMMIT;
