-- Migracion 012: Bloqueos de horario de cancha.
--
-- Modela los casos en que una cancha (o todas) no se pueden reservar por
-- un período: mantenimiento, feriado, evento privado, lluvia. Hasta ahora
-- el operador resolvía esto creando "reservas placebo" con nombres tipo
-- "MANTENIMIENTO" — feo, mezcla los reportes, fricción operativa.
--
-- Reglas:
--   - canchaid = NULL bloquea TODAS las canchas (ej. feriado nacional).
--   - hora_desde / hora_hasta = NULL ⇒ todo el día.
--   - motivo es texto libre (max 100 chars) que se muestra en el calendario.
--
-- `verificarConflictoTx` en canchaReserva.controller debe incluir un check
-- contra esta tabla además del check contra otras reservas, para que un
-- intento de reservar sobre un slot bloqueado devuelva 409 con motivo.
--
-- Idempotente: CREATE TABLE IF NOT EXISTS.

BEGIN;

CREATE TABLE IF NOT EXISTS cancha_bloqueo (
  canchabloqueoid         INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  canchaid                INTEGER,
  canchabloqueofecha      DATE        NOT NULL,
  canchabloqueohoradesde  TIME,
  canchabloqueohorahasta  TIME,
  canchabloqueomotivo     VARCHAR(100) NOT NULL DEFAULT '',
  usuarioid               VARCHAR(25),
  canchabloqueocreadoen   TIMESTAMP   NOT NULL DEFAULT NOW()
);

-- Lookup principal: "¿qué bloqueos aplican a esta fecha?"
CREATE INDEX IF NOT EXISTS idx_cancha_bloqueo_fecha
  ON cancha_bloqueo (canchabloqueofecha);

-- Lookup más específico para verificarConflicto.
CREATE INDEX IF NOT EXISTS idx_cancha_bloqueo_cancha_fecha
  ON cancha_bloqueo (canchaid, canchabloqueofecha);

COMMIT;
